name: basemental
description: Companion project for tutorial on audio_service plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_video_progress_bar: ^0.5.0
  get_it: ^7.1.2
  audio_service: ^0.18.2
  just_audio: ^0.9.18
  json_annotation: ^4.0.1
  socket_io_client: ^1.0.2
  get: ^4.6.1

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/